# this is a Stencil for Kubernetes ConfigMaps. It adds any stack environment variable tagged with kube-var to this file
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ${formation}
  name: ${concat(stackname, "-env-map")}
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
  labels:
    app: ${stackname}
data:
  ${envlist(2, "kube-var")}