apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: k8s-event-relay
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}    
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-event-relay
    spec:      
      containers:
      - name: k8s-event-relay
        imagePullPolicy: Always
        image: cloud66/k8s-event-relay:latest
        command: ["k8s-event-relay"]
        args: ["--upstream-host=https://app.cloud66.com", "--log=STDOUT", "--log-level=info", "--api=${env("CLOUD66_ACCOUNT_KEY")}", "--ctx=${formation["uuid"]}", "--ctx-type=formation"]