apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-event-relay
  namespace: c66-system
  labels:
    app: k8s-event-relay
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-event-relay
  template:
    metadata:
      labels:
        app: k8s-event-relay
    spec:
      tolerations:
        # Allow this pod to run anywhere
        - operator: "Exists"
      serviceAccountName: c66-user
      containers:
        - name: k8s-event-relay
          imagePullPolicy: IfNotPresent
          image: cloud66/k8s-event-relay:4.0.0
          command: ["k8s-event-relay"]
          args:
            - "--upstream-host=${account.cloud66_address}"
            - "--log=STDOUT"
            - "--log-level=info"
            - "--api=${account.api_key}"
