---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: ${formation.name}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: c66-system:external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: c66-system:external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: c66-system:external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: ${formation.name}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: ${formation.name}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: cloud66/external-dns@sha256:669e891edf9ffce86242f30120560a3d7ea79228dc5272451d33b8961aae0840
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=${endpoint_suffix}
        - --provider=zonedns
        - --zonedns-scheme=${container_net.scheme}
        - --zonedns-host=${container_net.host}
        - --zonedns-port=${container_net.port}
        env:
        - name: EXTERNAL_DNS_ZONEDNS_CLOUD66_ACCOUNT_API_KEY
          valueFrom:
            secretKeyRef:
              name: account-secrets
              key: api.key
      imagePullSecrets:
      - name: cloud66-user-registry-pull-secret
