---
# this is a Stencil for Kubernetes service.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ${formation.name}
  name: ${concat(service.name, "-ingress")}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: ${application.name}
    tier: ${service.name}
spec:
  # use the ingress.js transformer to automatically configure this ingress.
  # the following are examples and can be removed
  # rules:
  # - host: ${service.endpoint}
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: ${concat(service.name, "-svc")}
  #         servicePort: ${service.port.http}
  #
  # use the ssl.js transformer to add SSL to this ingress. Make sure you have cert_manager stencil added to your cluster
  # tls:
  # - secretName: ${concat(service.name, "-tls")}
  #   hosts:
  #   - ${service.endpoint}
