# this is a sample stencil (redis)
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${formation}
  name: redis
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}    
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
spec:
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${stackname}
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis  
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${formation}
  name: redis
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}    
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
  labels:
    app: ${stackname}
    tier: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: ${stackname}
    tier: redis

