# Secret store for private registry credentials
apiVersion: v1
kind: Secret
metadata:
  namespace: ${formation.name}
  name: cloud66-registry-pull-secret
data:
  .dockerconfigjson: ${registry_credentials()}
type: kubernetes.io/dockerconfigjson
---
# Secret store for stack config_store entries
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(application.name, "-configstore")}
  labels:
    app: ${application.name}
type: Opaque
data:
  ${configstore_list()}
---
# Secret store for stack environment variables tagged with "kube-secret"
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(application.name, "-environment-variables")}
  labels:
    app: ${application.name}
type: Opaque
data:
  ${envlist("kube-secret")}
