# Secret store for private registry credentials
apiVersion: v1
kind: Secret
metadata:
  namespace: ${formation.name}
  name: cloud66-registry-pull-secret
data:
  .dockerconfigjson: ${registry_credentials()}
type: kubernetes.io/dockerconfigjson