# Secret store for stack environment variables tagged with "kube-secret"
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(application.name, "-environment-variables")}
  labels:
    app: ${application.name}
type: Opaque
data:
  ${envlist("kube-secret")}
