# Secret store for account level secrets
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  namespace: ${formation.name}
  name: account-secrets
stringData:
  api.key: ${account.api_key}
---
# Secret store for stack config_store entries
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(application.name, "-configstore")}
  labels:
    app: ${application.name}
type: Opaque
data:
  ${base64(configstore_list())}
---
# Secret store for stack environment variables tagged with "kube-secret"
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(application.name, "-environment-variables")}
  labels:
    app: ${application.name}
type: Opaque
data:
  ${base64(envlist("kube-secret"))}
