# Secret store for stack config_store entries
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(application.name, "-configstore")}
  labels:
    app: ${application.name}
type: Opaque
data:
  ${configstore_list()}