# Secret store for private registry credentials
apiVersion: v1
kind: Secret
metadata:
  namespace: ${formation.name}
  name: cloud66-registry-pull-secret
  annotations:
    cloud66.com/formation-uuid: ${formation.uuid}
    cloud66.com/stencil-uuid: ${stencil.uuid}
    cloud66.com/snapshot-uid: ${snapshot.uid}
    cloud66.com/snapshot-gitref: ${snapshot.gitref}
data:
  .dockerconfigjson: ${registry_credentials()}
type: kubernetes.io/dockerconfigjson
---
# Secret store for stack config_store entries
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(stack.name, "-configstore")}
  annotations:
    cloud66.com/formation-uuid: ${formation.uuid}
    cloud66.com/stencil-uuid: ${stencil.uuid}
    cloud66.com/snapshot-uid: ${snapshot.uid}
    cloud66.com/snapshot-gitref: ${snapshot.gitref}
  labels:
    app: ${stack.name}
type: Opaque
data:
  ${configstore_list(2)}
---
# Secret store for stack environment variables tagged with "kube-secret"
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation.name}
  name: ${concat(stack.name, "-environment-variables")}
  annotations:
    cloud66.com/formation-uuid: ${formation.uuid}
    cloud66.com/stencil-uuid: ${stencil.uuid}
    cloud66.com/snapshot-uid: ${snapshot.uid}
    cloud66.com/snapshot-gitref: ${snapshot.gitref}
  labels:
    app: ${stack.name}
type: Opaque
data:
  ${envlist(2, "kube-secret")}
